# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.


# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "scikit" #air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

# Site Settings
title: "scikit-learn @ Fondation Inria"
email: social@scikit-learn.org
description: "The official website of the scikit-learn consortium, an open source library for machine learning in Python."
logo: assets/images/scikit-learn-logo.png
favicon: assets/images/scikit-learn-logo.png
baseurl: "/"
url: "https://scikit-learn-inria-fondation.github.io/website/" # the base hostname
twitter_username: scikit_learn
github_username:  scikit-learn
repository:  scikit-learn-inria-fondation/website

header:
  image: /assets/images/scikit-header.png

# Site-wide Search
search: true

# Format Dates
date_format: "%Y-%m-%d"

# Author
author:
  #name: ""
  #avatar: "/assets/images/"
  bio: "Open source library for machine learning in Python."
  #location: ""
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/scikit-learn-inria-fondation"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/sklearn_inria"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/company/scikit-learn-consortium/"


# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/scikit-learn-inria-fondation"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/sklearn_inria"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/company/scikit-learn-consortium/"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-archives
  - jekyll-target-blank
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-twitter-plugin
  - jekyll-polyglot

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-archives

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone:


# SEO Related
#google_site_verification : 
#bing_site_verification   :
#yandex_site_verification :
#naver_site_verification  :

# Google Analytics
analytics:
  provider: "google" #false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id: UA-22606712-3

# Exclude from processing
exclude:
  - README
  - _posts/template
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Reading Files
include:
  - .htaccess
  - _pages
  - _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Archives
#category_archive:
#  type: jekyll-archives
#  path: /categories/
#tag_archive:
#  type: jekyll-archives
#  path: /tags/

#jekyll-archives:
#  enabled:
#    - categories
#    - tags
#  layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#  permalinks:
#     category: '/categories/:name/'
#     tag: '/tags/:name/'

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

collections:
  archives:
    output: true
    permalink: /archives/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      sidebar:
        nav: "docs"
      show_date: true
      read_time: true
      related: true
      comments: true
      share: true
      author_profile: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "docs"

#Polyglot

languages: ["en", "fr"]
default_lang: "fr"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true
